import {A, D, G, S, W} from "../controller/tiles"

export const LOBBY_RAW = [
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
  [A, A, W, W, W, A, A, A, A, S, A, S, A, A, A, A, A, A, A, A, A],
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
  [G, G, G, G, G, G, G, G, G, G, G, G, G, G, G, G, G, G, G, G, G],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D],
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
  [A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A, A],
]